# Generated by Django 5.0.6 on 2024-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
