# Generated by Django 5.0.6 on 2024-08-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_test_profile_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='budget',
            new_name='total',
        ),
    ]
