# Generated by Django 5.0.6 on 2024-08-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_budget_profile_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
