# Generated by Django 5.0.6 on 2024-09-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfpUrl',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/009/292/244/non_2x/default-avatar-icon-of-social-media-user-vector.jpg', max_length=255),
        ),
    ]
