# Generated by Django 5.0.6 on 2024-07-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=7),
        ),
    ]
