# Generated by Django 5.0.6 on 2024-07-22 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
