# Generated by Django 5.0.6 on 2024-07-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=7),
        ),
    ]
