# Generated by Django 5.0.6 on 2024-07-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='category',
        ),
    ]
