# Generated by Django 5.0.6 on 2024-10-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_transaction_date'),
        ('users', '0006_profile_pfpurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyyy_mm', models.CharField(max_length=7)),
                ('budget_set', models.FloatField()),
                ('amount_spent', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
